baseURL = 'https://saisamphan.world/'
languageCode = 'en-us'
theme = "mainroad"

baseurl = "/"
paginate = "10" # Number of posts per page
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Params.logo]
title = 'Saisamphan'
subtitle = "New Perspectives for " # Logo subtitle
image = "img/placeholder.png"

[Author]
name = "F. Deininger"
bio = "He is a successful blogger or writer. Nobody knows it."
avatar = "img/avatar.png"

[Params]
description = "John Doe's Personal blog about everything" # Description of your site
opengraph = true
twitter_cards = false
readmore = false # Show "Read more" button in list if true
authorbox = true
pager = true
post_meta = ["date", "categories", "author"] # Order of post meta information
mainSections = ["blog", "page"]

[Params.style.vars]
highlightColor = "#ff667666"

[Params.sidebar]
home = "right"   # Configure layout for home page
list = "right"   # Configure layout for list pages
single = "right" # Configure layout for single pages
# Enable widgets in given order
widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
recent_num = 5 # Set the number of articles in the "Recent articles" widget
tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
# Enable parts of social widget
email = "example@example.com"
facebook = "username"
twitter = "username"